name = "EDKit"
uuid = "f6058819-fd6f-45d3-a3c8-4753d8c54d1a"
authors = ["JayRen <jieren3996@foxmail.com>"]
version = "0.4.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1.6"
