#-------------------------------------------------------------------------------------------------------------------------
# Parity + Flip
#-------------------------------------------------------------------------------------------------------------------------
export ParityFlipBasis
"""
    ParityFlipBasis

Basis reduced simultaneously by reflection parity and spin-flip parity.

This basis combines the two commuting involutions generated by reversal and
spin flip. Each representative may have an orbit of size 1, 2, or 4 depending
on stabilizers.
"""
struct ParityFlipBasis{Ti <: Integer} <: AbstractPermuteBasis
    dgt::Vector{Ti}       # Digits
    I::Vector{Ti}         # Representing states
    R::Vector{Float64}    # Normalization
    P::Int                # {±1}, parity
    Z::Int                # {±1}, spin-flip parity
    M::Int                # base^length + 1
    B::Ti                 # Base
end
#-------------------------------------------------------------------------------------------------------------------------
"""
    ParityFlipJudge

Internal selector for the combined parity/flip basis.
"""
struct ParityFlipJudge{TF, T}
    F::TF                 # Projective selection
    P::Int64              # Parity
    Z::Int64              # Spin-flip parity
    B::T                  # Base
    MAX::Int              # base^length + 1
    C::Vector{Float64}    # [2, 2sqrt(2), 0, 4]
end
#-------------------------------------------------------------------------------------------------------------------------
"""
    double_parity_check(dgt, i, base, max, p, z)

Check whether product state `i` is canonical under the joint action of
reflection and spin flip, and return the size class of its stabilizer orbit.

The second return value is an index into the normalization lookup table used by
[`ParityFlipJudge`](@ref).
"""
function double_parity_check(dgt, i, base, max, p, z)
    (Ip = rindex(dgt, base=base)) < i && return (false, 1)
    (Iz = max - i) < i && return (false, 3)
    (Ipz = max - Ip) < i && return (false, 3)
    N = 1
    if isequal(Ip, i)
        isone(p) || return (false, 3)
        N += 1
    end
    if isequal(Iz, i)
        isone(z) || return (false, 3)
        N += 1
    end
    if isequal(Ipz, i)
        isone(p*z) || return (false, 3)
        N += 1
    end            
    true, N
end
#-------------------------------------------------------------------------------------------------------------------------
"""
    (judge::ParityFlipJudge)(dgt, i)

Return whether a state should be kept in the combined parity/flip basis and the
corresponding normalization factor.
"""
function (judge::ParityFlipJudge)(dgt::AbstractVector{<:Integer}, i::Integer)
    # If there is a projective selection function F, check `F(dgt)` first
    isnothing(judge.F) || judge.F(dgt) || return (false, 0.0)
    # f may not be reflection/flip-invariant: every orbit partner must satisfy f.
    if !isnothing(judge.F)
        flp = judge.B .- 1 .- dgt
        (judge.F(reverse(dgt)) && judge.F(flp) && judge.F(reverse(flp))) || return (false, 0.0)
    end

    Q, n = double_parity_check(dgt, i, judge.B, judge.MAX, judge.P, judge.Z)
    Q, judge.C[n]
end
#-------------------------------------------------------------------------------------------------------------------------
"""
    ParityFlipBasis(dtype::DataType=Int64; L, f=nothing, p, z, N=nothing, base=2, alloc=1000, threaded=true, small_N=true)

Construct a basis reduced by both reflection parity `p` and spin-flip parity
`z`.
"""
function ParityFlipBasis(
    dtype::DataType=Int64; L::Integer, f=nothing, p::Integer, z::Integer, N::Union{Nothing, Integer}=nothing,
    base::Integer=2, alloc::Integer=1000, threaded::Bool=true, small_N::Bool=true
)
    @assert isone(p) || isone(-p) "Invalid parity"
    @assert isnothing(N) || isequal(2N, L*(base-1)) "N = $N not compatible."
    _check_index_capacity(dtype, base, L)
    base = convert(dtype, base)
    MAX = base ^ L + 1
    C = [2.0, 2*sqrt(2), 0.0, 4.0]
    g = (small_N || isnothing(N)) ? f : _charge_predicate(f, L*(base-1) - N)
    judge = ParityFlipJudge(g, p, z, base, MAX, C)
    I, R = _run_selectindexnorm(judge, L, N, base, alloc, threaded, small_N)
    ParityFlipBasis(zeros(dtype, L), I, R, p, z, MAX, base)
end
#-------------------------------------------------------------------------------------------------------------------------
"""
    index(b::ParityFlipBasis, dgt)

Interpret `dgt` in the combined parity/flip basis and return the
coefficient/index pair for the corresponding representative. The 1-arg form
is provided by the generic fallback in `AbstractBasis.jl`.
"""
function index(b::ParityFlipBasis, dgt::AbstractVector)
    I0 = index(dgt, base=b.B)
    state = I0 - one(eltype(b.I))
    TI = eltype(b.I)
    base = TI(b.B)
    L = length(dgt)
    maxstate = base^L - one(TI)
    Ip = _int_reverse(state, L, base) + one(TI)
    Iz = _int_spinflip(state, maxstate) + one(TI)
    Ipz = _int_spinflip(Ip - one(TI), maxstate) + one(TI)
    Ir = min(I0, Iz, Ip, Ipz)
    i = binary_search(b.I, Ir)
    iszero(i) && return (zero(eltype(b)), one(b.B))
    N = if isequal(Ir, I0)
        b.R[i]
    elseif isequal(Ir, Ip)
        b.P * b.R[i]
    elseif isequal(Ir, Iz)
        b.Z * b.R[i]
    else
        b.P * b.Z * b.R[i]
    end
    N, i
end
#-------------------------------------------------------------------------------------------------------------------------
"""
    order(b::ParityFlipBasis)

Return the maximum symmetry-orbit size for the combined parity/flip action.
"""
order(b::ParityFlipBasis) = 4
eltype(::ParityFlipBasis) = Float64
copy(b::ParityFlipBasis) = ParityFlipBasis(deepcopy(b.dgt), b.I, b.R, b.P, b.Z, b.M, b.B)
